baseurl = "//graydh.github.io/"
title = "Declan Gray-Mullen"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "graydh"

[params]
    author = "Declan Gray-Mullen"
    info = "Math Tutor @ Williston Northampton"
    description = "Declan's personal website"
    keywords = "developer,personal"
    avatarurl = "/images/declaniconavatar_smaller.jpg"

    footercontent = ""

    hidecredits = true
    hidecopyright = true

    inverted = true

    rtl = false

    math = true

    colorScheme = "dark"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "http://github.com/graydh/"
[[params.social]]
    name = "Linkedin"
    icon = "fa fa-linkedin"
    weight = 2
    url = "http://www.linkedin.com/in/declangraymullen/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "about/"
[[menu.main]]
    name = "Contact Me"
    weight = 3
    url = "contact/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"